import { GoogleGenAI, Modality } from "@google/genai";
import { AspectRatio } from "../constants";

// This function is memoized to avoid re-creating the GoogleGenAI instance on every call.
const getGenAI = (() => {
  let ai: GoogleGenAI | null = null;
  return () => {
    if (ai) return ai;
    const apiKey = process.env.API_KEY;
    if (!apiKey) {
      throw new Error("API_KEY environment variable is not set.");
    }
    ai = new GoogleGenAI({ apiKey });
    return ai;
  }
})();

export const editImageCloud = async (
  base64ImageData: string,
  mimeType: string,
  prompt: string
): Promise<string> => {
  const ai = getGenAI();
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        {
          inlineData: {
            data: base64ImageData,
            mimeType: mimeType,
          },
        },
        {
          text: prompt,
        },
      ],
    },
    config: {
      responseModalities: [Modality.IMAGE],
    },
  });

  const parts = response.candidates?.[0]?.content?.parts;
  if (parts) {
    for (const part of parts) {
      if (part.inlineData) {
        const { data, mimeType } = part.inlineData;
        return `data:${mimeType};base64,${data}`;
      }
    }
  }
  
  throw new Error("No image was returned from the API.");
};


export const generateImageCloud = async (
    prompt: string,
    aspectRatio: AspectRatio,
): Promise<string> => {
    const ai = getGenAI();
    const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: prompt,
        config: {
            numberOfImages: 1,
            outputMimeType: 'image/png',
            aspectRatio: aspectRatio,
        },
    });

    const generatedImage = response.generatedImages?.[0];
    if (generatedImage && generatedImage.image?.imageBytes) {
        const base64ImageBytes = generatedImage.image.imageBytes;
        return `data:image/png;base64,${base64ImageBytes}`;
    }

    throw new Error("No image was generated by the API.");
};